/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

buildscript {
    val kotlinVersion by extra { "1.3.20"}

    repositories {
        jcenter()
        maven {
            url = uri("https://jitpack.io")
        }
    }
    dependencies {
        classpath(group = "org.jetbrains.kotlin", name = "kotlin-script-util", version = kotlinVersion)
        classpath("com.improve_future:harmonica:1.1.26")
    }
}

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.72"
    kotlin("plugin.serialization") version "1.3.70"

    // Apply the application plugin to add support for building a CLI application.
    application
}

apply(plugin = "jarmonica")

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
    maven {
        url = uri("https://jitpack.io")
    }
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    implementation("net.dv8tion:JDA:4.1.1_157")

    implementation("com.jagrosh:jda-utilities:3.0.3")

    implementation("com.charleskorn.kaml:kaml:0.17.0")

    implementation("org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.20.0")

    implementation("org.jetbrains.exposed:exposed-core:0.25.1")

    implementation("org.jetbrains.exposed:exposed-dao:0.25.1")

    implementation("org.jetbrains.exposed:exposed-jdbc:0.25.1")

    implementation("mysql:mysql-connector-java:8.0.20")

    implementation("com.zaxxer:HikariCP:3.4.5")

    implementation("com.improve_future:harmonica:1.1.26")

    implementation("org.reflections:reflections:0.9.12")

    implementation("io.github.microutils:kotlin-logging:1.7.10")

    implementation("ch.qos.logback:logback-classic:1.2.3")
}

application {
    // Define the main class for the application.
    mainClassName = "com.it_finne.dqx_drakee.AppKt"
}

tasks.withType<KotlinCompile> {
    kotlinOptions {
        jvmTarget = "1.8"
    }
}

extensions.extraProperties["migrationPackage"] = "com.it_finne.dqx_drakee.db"
