/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/* =============== PROJECT SETTINGS =============== */
val projectPackage: String = "com.it_finne.discordbot_template_for_kotlin"
val projectMainClass: String = "AppKt"
/* ================================================ */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.72"
    id("org.flywaydb.flyway") version "7.5.4"
    kotlin("plugin.serialization") version "1.3.70"

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    implementation("net.dv8tion:JDA:4.1.1_157")

    implementation("com.jagrosh:jda-utilities:3.0.3")

    implementation("com.charleskorn.kaml:kaml:0.17.0")

    implementation("org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.20.0")

    implementation("org.jetbrains.exposed:exposed-core:0.25.1")

    implementation("org.jetbrains.exposed:exposed-dao:0.25.1")

    implementation("org.jetbrains.exposed:exposed-jdbc:0.25.1")

    implementation("org.jetbrains.exposed:exposed-java-time:0.29.1")

    implementation("mysql:mysql-connector-java:8.0.20")

    implementation("com.zaxxer:HikariCP:3.4.5")

    implementation("io.github.microutils:kotlin-logging:1.7.10")

    implementation("ch.qos.logback:logback-classic:1.2.3")
}

application {
    // Define the main class for the application.
    mainClassName = "${projectPackage}.${projectMainClass}"
}

tasks.withType<KotlinCompile> {
    kotlinOptions {
        jvmTarget = "1.8"
    }
}

tasks.withType<Jar> {
    manifest {
        attributes["Main-Class"] = "${projectPackage}.${projectMainClass}"
    }

    from({
        configurations.runtimeClasspath.get().filter { it.name.endsWith("jar") }.map { zipTree(it) }
    })
}

flyway {
    url = System.getenv("FLYWAY_URL")
    user = System.getenv("FLYWAY_USER")
    password = System.getenv("FLYWAY_PASSWORD")
}
